environment variables 8

diff --git a/.github/workflows/deploy-function.yml b/.github/workflows/deploy-function.yml
--- a/.github/workflows/deploy-function.yml
+++ b/.github/workflows/deploy-function.yml
@@ -66,6 +66,7 @@ jobs:
           SEND_GMAIL_APP_PASSWORD: ${{ secrets.SEND_GMAIL_APP_PASSWORD }}
           TEST_SECRET: ${{ secrets.TEST_SECRET }}
         run: |
+          sudo apt-get install -y jq
           zip -r function.zip . -x@.zipignore
           aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://function.zip
           ENV_VARS=("SDK_TYPE" "SDK_PROJECT_ID" "SDK_PRIVATE_KEY_ID" "SDK_PRIVATE_KEY" "SDK_CLIENT_EMAIL" "SDK_CLIENT_ID" "SDK_CLIENT_X509_CERT_URL" "FIREBASE_DATABASE_URL" "FIREBASE_API_KEY" "FIREBASE_USERNAME" "FIREBASE_PASSWORD" "SEND_GMAIL_USERNAME" "SEND_GMAIL_APP_PASSWORD" "TEST_SECRET")
@@ -74,14 +75,23 @@ jobs:
             JSON_ENV_VARS="$JSON_ENV_VARS\"$VAR\":\"${!VAR}\","
           done
           JSON_ENV_VARS="${JSON_ENV_VARS::-1}}"  # Remove the trailing comma and close the JSON object.
+          ENV_VARS_FORMATTED=$(echo $JSON_ENV_VARS | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]')
+          MAX_RETRIES=5
+          RETRY_COUNT=0
           while true; do
             if aws lambda update-function-configuration --function-name $LAMBDA_FUNCTION_NAME \
-              --environment "Variables=$JSON_ENV_VARS"; then
+              --environment "Variables={$ENV_VARS_FORMATTED}"; then
               echo "Update function configuration succeeded"
               break
             else
-              echo "Update function configuration failed, retrying in 10 seconds"
-              sleep 10
+              RETRY_COUNT=$((RETRY_COUNT+1))
+              if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
+                echo "Update function configuration failed after $MAX_RETRIES attempts, exiting"
+                exit 1
+              else
+                echo "Update function configuration failed, retrying in 10 seconds"
+                sleep 10
+              fi
             fi
           done
         working-directory: ${{ github.workspace }}
